services:
  tgbot:
    build:
      context: .
      dockerfile: ./app/Dockerfile_tgbot
      args:
        - ARG POSTGRES_URL
        - ARG REDIS_URL
        - ARG REDIS_PASSWORD
        - ARG TG_TOKEN
        - ARG ADMIN_ID
        - ARG PROXY_TOKEN
        - ARG ENV
    env_file:
          - .env
    image: yt2mp3bot
    restart: always
    networks:
      - default

  worker:
    build:
      context: .
      dockerfile: ./app/Dockerfile_worker
      args:
        - ARG POSTGRES_URL
        - ARG REDIS_URL
        - ARG REDIS_PASSWORD
        - ARG TG_TOKEN
        - ARG ADMIN_ID
        - ARG PROXY_TOKEN
        - ARG ENV
    env_file:
          - .env
    image: yt2mp3_worker
    restart: always
    volumes:
      - audio_data:/app/audio
    networks:
      - default



networks:
  default:
    external:
      name: ${NETWORK_NAME}


volumes:
  audio_data:

