services:
  tgbot:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        - OPENAI_TOKEN
        - POSTGRES_URL
        - REDIS_PASSWORD
    env_file:
          - .env
    image: pomidor-server
    ports:
      - "${SERVER_PORT}:8000"
    restart: always

  worker:
    build:
      context: .
      dockerfile: ./app_worker/Dockerfile
      args:
        - OPENAI_TOKEN
        - POSTGRES_URL
        - REDIS_PASSWORD
    env_file:
          - .env
    image: pomidor-worker
    restart: always
    volumes:
      - audio_data:/app/audio




  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT}:5432"     
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 300M

  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"


volumes:
  postgres_data:
  audio_data:

