# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Copy & install requirements file for scripts
COPY ../scripts/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy &  install tgmediabot library
COPY ../tgmediabot /app/tgmediabot
RUN pip install --no-cache-dir /app/tgmediabot

# Copy scripts into container at /app
COPY ../scripts /app/scripts


# Arguments
ARG POSTGRES_URL
ARG REDIS_URL
ARG REDIS_PASSWORD
ARG TG_TOKEN
ARG ADMIN_ID
ARG PROXY_TOKEN
ARG ENV

# Set arg as environment variable
ENV POSTGRES_URL=$POSTGRES_URL
ENV REDIS_URL=$REDIS_URL
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV TG_TOKEN=$TG_TOKEN
ENV ADMIN_ID=$ADMIN_ID
ENV PROXY_TOKEN=$PROXY_TOKEN
ENV ENV=$ENV


# run tests
WORKDIR /app/
RUN pip install pytest
COPY ../tests /app/tests
RUN pytest 


# Set the working directory to /app/scripts
WORKDIR /app/scripts

CMD ["python", "/app/scripts/mybot.py"]

