name: Deploy

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy .env file
      run: |
        cp /home/gituser/env_files/ytbot.env ./.env
        cp /home/gituser/env_files/ytbot_proxies.txt ./app/.proxylist.env
        


    - name: Build Docker Compose services
      run: |
        docker-compose -f ./docker-compose.yml build


    - name: Run Docker Compose services
      run: |
        docker-compose -f ./docker-compose.yml up -d

