name: Deploy

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

      - name: Copy .env file
        env:
          ENV_FILE_PATH: ${{ secrets.ENV_FILE_PATH }}
        run: |
          cp $ENV_FILE_PATH ./.env


    - name: Build Docker Compose services
      run: |
        docker compose -f ./docker-compose.yml build


    - name: Run Docker Compose services
      run: |
        docker compose -f ./docker-compose.yml up -d

